main: de.lama.banmanager.main.Main
name: BanManager
version: 1.0
author: Lama_Agent

commands:
  ban:
    description: Bans a player permanent.
  tempban:
    description: Bans a player temporarily.
  unban:
    description: Unbans a player.
  check:
    description: Gives some information about a player.
